version: '3.8'

services:
  mop-platform:
    container_name: mop-platform
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=file:/app/data/dev.db
      # Add other env vars here from your .env file
      - NEXTAUTH_SECRET=your_auth_secret_here
      - NEXTAUTH_URL=http://localhost:3000
    volumes:
      # Persist SQLite database (Mount single file into writable directory)
      - ./prisma/dev.db:/app/data/dev.db
